[package]
name = "bounce-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
base62 = "2.0"
reqwest = { version = "0.12", features = ["blocking"] }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[features]
debug = []
